export enum Provincia {
  A_Coruna = "A Coruña",
  Alava = "Álava",
  Albacete = "Albacete",
  Alicante = "Alicante",
  Almeria = "Almería",
  Asturias = "Asturias",
  Avila = "Ávila",
  Badajoz = "Badajoz",
  Barcelona = "Barcelona",
  Burgos = "Burgos",
  Caceres = "Cáceres",
  Cadiz = "Cádiz",
  Cantabria = "Cantabria",
  Castellon = "Castellón",
  Ciudad_Real = "Ciudad Real",
  Cordoba = "Córdoba",
  Cuenca = "Cuenca",
  Gerona = "Gerona",
  Granada = "Granada",
  Guadalajara = "Guadalajara",
  Guipuzcoa = "Guipúzcoa",
  Huelva = "Huelva",
  Huesca = "Huesca",
  Jaen = "Jaén",
  La_Rioja = "La Rioja",
  Las_Palmas = "Las Palmas",
  Leon = "León",
  Lerida = "Lérida",
  Lugo = "Lugo",
  Madrid = "Madrid",
  Malaga = "Málaga",
  Murcia = "Murcia",
  Navarra = "Navarra",
  Orense = "Orense",
  Palencia = "Palencia",
  Pontevedra = "Pontevedra",
  Salamanca = "Salamanca",
  Santa_Cruz_de_Tenerife = "Santa Cruz de Tenerife",
  Segovia = "Segovia",
  Sevilla = "Sevilla",
  Soria = "Soria",
  Tarragona = "Tarragona",
  Teruel = "Teruel",
  Toledo = "Toledo",
  Valencia = "Valencia",
  Valladolid = "Valladolid",
  Vizcaya = "Vizcaya",
  Zamora = "Zamora",
  Zaragoza = "Zaragoza"
}

export const Provincia2StringMapper: Record<Provincia, string> = {
  [Provincia.A_Coruna]: "A Coruña",
  [Provincia.Alava]: "Álava",
  [Provincia.Albacete]: "Albacete",
  [Provincia.Alicante]: "Alicante",
  [Provincia.Almeria]: "Almería",
  [Provincia.Asturias]: "Asturias",
  [Provincia.Avila]: "Ávila",
  [Provincia.Badajoz]: "Badajoz",
  [Provincia.Barcelona]: "Barcelona",
  [Provincia.Burgos]: "Burgos",
  [Provincia.Caceres]: "Cáceres",
  [Provincia.Cadiz]: "Cádiz",
  [Provincia.Cantabria]: "Cantabria",
  [Provincia.Castellon]: "Castellón",
  [Provincia.Ciudad_Real]: "Ciudad Real",
  [Provincia.Cordoba]: "Córdoba",
  [Provincia.Cuenca]: "Cuenca",
  [Provincia.Gerona]: "Gerona",
  [Provincia.Granada]: "Granada",
  [Provincia.Guadalajara]: "Guadalajara",
  [Provincia.Guipuzcoa]: "Guipúzcoa",
  [Provincia.Huelva]: "Huelva",
  [Provincia.Huesca]: "Huesca",
  [Provincia.Jaen]: "Jaén",
  [Provincia.La_Rioja]: "La Rioja",
  [Provincia.Las_Palmas]: "Las Palmas",
  [Provincia.Leon]: "León",
  [Provincia.Lerida]: "Lérida",
  [Provincia.Lugo]: "Lugo",
  [Provincia.Madrid]: "Madrid",
  [Provincia.Malaga]: "Málaga",
  [Provincia.Murcia]: "Murcia",
  [Provincia.Navarra]: "Navarra",
  [Provincia.Orense]: "Orense",
  [Provincia.Palencia]: "Palencia",
  [Provincia.Pontevedra]: "Pontevedra",
  [Provincia.Salamanca]: "Salamanca",
  [Provincia.Santa_Cruz_de_Tenerife]: "Santa Cruz de Tenerife",
  [Provincia.Segovia]: "Segovia",
  [Provincia.Sevilla]: "Sevilla",
  [Provincia.Soria]: "Soria",
  [Provincia.Tarragona]: "Tarragona",
  [Provincia.Teruel]: "Teruel",
  [Provincia.Toledo]: "Toledo",
  [Provincia.Valencia]: "Valencia",
  [Provincia.Valladolid]: "Valladolid",
  [Provincia.Vizcaya]: "Vizcaya",
  [Provincia.Zamora]: "Zamora",
  [Provincia.Zaragoza]: "Zaragoza"
};
